# Generated by Django 4.2.16 on 2026-07-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fleet", "0002_auto_20211109_1456"),
        ("geography", "0002_busstop"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="fleet.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="fleet.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusShiftEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                (
                    "bus_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="operations.busshift",
                    ),
                ),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_entries",
                        to="geography.busstop",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="busshiftentry",
            constraint=models.UniqueConstraint(
                fields=("bus_shift", "bus_stop"), name="unique_bus_stop_per_shift"
            ),
        ),
    ]
