# Generated by Django 4.2.16 on 2026-07-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="geography.place",
                    ),
                ),
            ],
        ),
    ]
